hops: 2
seeds: []
seeds_for: {}
contracts_paths: []
glossary_path: docs/glossary.md
metrics:
  enabled: true
  weekly_reports: true
  event_tracking: true
exclude_patterns:
- '**/__pycache__/**'
- '**/node_modules/**'
- '**/.git/**'
include_patterns:
- y
- y
- y
- y
analysis_options:
  complexity_analysis: true
  side_effects: true
  dependencies: true
ci_integration:
  enabled: true
  platform: y
  fail_on_issues: true
  generate_reports: true
ide_integration:
  enabled: true
  type: y
  gutter_annotations: true
  quick_peek: true
