"""CI command: scan + lens + tour artifacts for pipelines (extracted from main)."""

from __future__ import annotations

import json
import os
import pathlib
from typing import Any

import typer
from rich.console import Console
from rich.progress import (
    BarColumn,
    Progress,
    SpinnerColumn,
    TextColumn,
    TimeElapsedColumn,
)

from ucli.analyzers.registry import build_repo_map
from ucli.lens.lens import lens_from_seeds, rank_by_error_proximity, write_tour_md
from ucli.metrics.ttu import record as ttu_record


def _complexity_value(raw: Any) -> int:
    if isinstance(raw, dict):
        return int(raw.get("cyclomatic", 0) or 0)
    try:
        return int(raw or 0)
    except (TypeError, ValueError):
        return 0


def generate_ci_report(repo_map: dict[str, Any], lens: dict[str, Any], scan_path: str) -> str:
    """Generate comprehensive CI report markdown."""
    functions = repo_map.get("functions", {})
    functions_count = len(functions)

    total_complexity = sum(
        _complexity_value(func.get("complexity", 0)) for func in functions.values()
    )
    avg_complexity = total_complexity / functions_count if functions_count > 0 else 0

    high_complexity_count = sum(
        1 for func in functions.values() if _complexity_value(func.get("complexity", 0)) > 10
    )
    side_effects_count = sum(1 for func in functions.values() if func.get("side_effects", []))

    report = f"""# Understand-First CI Report

## Analysis Summary

- **Scan Path**: `{scan_path}`
- **Functions Analyzed**: {functions_count}
- **Total Complexity**: {total_complexity}
- **Average Complexity**: {avg_complexity:.1f}
- **High Complexity Functions**: {high_complexity_count}
- **Functions with Side Effects**: {side_effects_count}

## Understanding Lens

- **Seeds**: {len(lens.get("lens", {}).get("seeds", []))}
- **Functions in Lens**: {len(lens.get("functions", {}))}

## Recommendations

"""

    if high_complexity_count > 0:
        report += f"- Consider refactoring {high_complexity_count} high-complexity functions\n"

    if side_effects_count > 0:
        report += f"- Review {side_effects_count} functions with side effects\n"

    if avg_complexity > 5:
        report += "- Overall complexity is high - consider architectural improvements\n"

    if functions_count == 0:
        report += "- No functions found - check scan path and file patterns\n"

    report += """
## Next Steps

1. Review the understanding tour for key insights
2. Address any high-complexity functions
3. Document side effects and their implications
4. Update understanding artifacts as code evolves

*Generated by Understand-First CI*
"""

    return report


def run_ci(
    scan_path: str,
    output_dir: str,
    *,
    fail_on_issues: bool = True,
    generate_report: bool = True,
) -> None:
    """Run Understand-First analysis for CI/CD pipeline with enhanced reporting."""
    console = Console()

    try:
        os.makedirs(output_dir, exist_ok=True)

        console.print("[bold blue]🔍 Scanning repository...[/bold blue]")
        repo_map_path = os.path.join(output_dir, "repo.json")

        with Progress(
            SpinnerColumn(),
            TextColumn("[progress.description]{task.description}"),
            BarColumn(),
            TextColumn("[progress.percentage]{task.percentage:>3.0f}%"),
            TimeElapsedColumn(),
            console=console,
        ) as progress:
            scan_task = progress.add_task("Scanning codebase...", total=100)
            progress.update(scan_task, advance=50)

            result = build_repo_map(pathlib.Path(scan_path))
            progress.update(scan_task, advance=50)

            with open(repo_map_path, "w", encoding="utf-8") as f:
                json.dump(result, f, indent=2)

        console.print(f"[green]✓ Repository map generated: {repo_map_path}[/green]")

        console.print("[bold blue]🎯 Generating understanding lens...[/bold blue]")
        lens_path = os.path.join(output_dir, "lens.json")

        functions = list(result.get("functions", {}).keys())
        seeds = functions[:3] if functions else []

        if seeds:
            lens = lens_from_seeds(seeds, result)
            rank_by_error_proximity(lens)

            with open(lens_path, "w", encoding="utf-8") as f:
                json.dump(lens, f, indent=2)

            console.print(f"[green]✓ Understanding lens generated: {lens_path}[/green]")
        else:
            console.print("[yellow]⚠ No functions found for lens generation[/yellow]")
            lens = {"functions": {}, "lens": {"seeds": []}}

        console.print("[bold blue]🗺️ Generating understanding tour...[/bold blue]")
        tour_path = os.path.join(output_dir, "tour.md")

        if lens.get("functions"):
            tour_md = write_tour_md(lens)
            with open(tour_path, "w", encoding="utf-8") as f:
                f.write(tour_md)
            console.print(f"[green]✓ Understanding tour generated: {tour_path}[/green]")
        else:
            console.print("[yellow]⚠ No lens data for tour generation[/yellow]")

        if generate_report:
            console.print("[bold blue]📊 Generating CI report...[/bold blue]")
            report_path = os.path.join(output_dir, "ci-report.md")

            report_content = generate_ci_report(result, lens, scan_path)
            with open(report_path, "w", encoding="utf-8") as f:
                f.write(report_content)
            console.print(f"[green]✓ CI report generated: {report_path}[/green]")

        issues: list[str] = []
        functions_count = len(result.get("functions", {}))

        if functions_count == 0:
            issues.append("No functions found in codebase")

        high_complexity = []
        for func_name, func_data in result.get("functions", {}).items():
            complexity = _complexity_value(func_data.get("complexity", 0))
            if complexity > 10:
                high_complexity.append(f"{func_name} (complexity: {complexity})")

        if high_complexity:
            issues.append(f"High complexity functions found: {', '.join(high_complexity[:3])}")

        side_effects = []
        for func_name, func_data in result.get("functions", {}).items():
            effects = func_data.get("side_effects", [])
            if effects:
                side_effects.append(f"{func_name}: {', '.join(effects)}")

        if side_effects:
            issues.append(f"Functions with side effects: {', '.join(side_effects[:3])}")

        if issues:
            console.print("\n[yellow]⚠ Issues detected:[/yellow]")
            for issue in issues:
                console.print(f"  • {issue}")

            if fail_on_issues:
                console.print("\n[red]❌ CI failed due to understanding issues[/red]")
                raise typer.Exit(1) from None
            console.print("\n[yellow]⚠ CI completed with warnings[/yellow]")
        else:
            console.print("\n[green]✅ CI completed successfully - no issues detected[/green]")

        summary = {
            "scan_path": scan_path,
            "output_dir": output_dir,
            "functions_analyzed": functions_count,
            "issues_found": len(issues),
            "artifacts_generated": [
                a
                for a in [
                    "repo.json",
                    "lens.json" if seeds else None,
                    "tour.md" if lens.get("functions") else None,
                    "ci-report.md" if generate_report else None,
                ]
                if a is not None
            ],
            "issues": issues,
        }

        summary_path = os.path.join(output_dir, "ci-summary.json")
        with open(summary_path, "w", encoding="utf-8") as f:
            json.dump(summary, f, indent=2)

        console.print(f"\n[green]✓ CI analysis completed. Summary: {summary_path}[/green]")

        ttu_record(
            "ci_completed",
            {
                "functions_analyzed": functions_count,
                "issues_found": len(issues),
                "artifacts_generated": len(summary["artifacts_generated"]),
            },
        )

    except typer.Exit:
        raise
    except Exception as e:
        console.print(f"[red]Error during CI analysis:[/red] {str(e)}")
        raise typer.Exit(1) from None
