# Example Fixture for custom Project

This fixture demonstrates how to test the understanding generated by Understand-First.

## Usage

Run this fixture to verify that the understanding tour can be executed:

```bash
u tour_run --fixtures fixtures maps/lens.json
```

## Customization

Modify this fixture to match your project's specific requirements and test scenarios.
