apiVersion: apps/v1
kind: Deployment
metadata:
  name: understand-first-commenter
  labels:
    app: understand-first-commenter
spec:
  replicas: 3
  selector:
    matchLabels:
      app: understand-first-commenter
  template:
    metadata:
      labels:
        app: understand-first-commenter
    spec:
      containers:
      - name: commenter
        image: understand-first/commenter:latest
        imagePullPolicy: Always
        env:
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: github-secrets
              key: token
        - name: REPOSITORY
          value: "your-org/your-repo"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: understand-first-commenter-service
spec:
  selector:
    app: understand-first-commenter
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: Secret
metadata:
  name: github-secrets
type: Opaque
data:
  token: <base64-encoded-github-token>
