name: Python CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install ruff

      - name: Lint
        run: ruff check .

      - name: Compose contracts and generate Lean stubs
        run: |
          python u.py contracts compose -i contracts/contracts_from_openapi.yaml -i contracts/contracts_from_proto.yaml -o contracts/contracts.yaml
          python u.py contracts lean-stubs contracts/contracts.yaml -o contracts/lean/
          python u.py contracts verify-lean contracts/contracts.yaml -l contracts/lean

      - name: Run tests
        run: pytest -q
