name: Publish PyPI
on:
  workflow_dispatch: {}
  release:
    types: [published]
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: |
          python -m pip install --upgrade build
          cd cli && python -m build
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: cli/dist
          skip-existing: true
