name: Tour Must Pass
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  tour:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -e cli fastapi uvicorn requests grpcio grpcio-tools
      - name: Build repo map
        run: |
          u scan . -o maps/repo.json || true
      - name: Create lens from PR files
        run: |
          CHANGED=$(git diff --name-only HEAD~1 | tr '\n' ' ')
          u lens from-seeds --seed $CHANGED --map maps/repo.json -o maps/lens.json || true
      - name: Generate gRPC Python code
        run: |
          python -m grpc_tools.protoc -I examples/apis             --python_out=examples/apis/gen             --grpc_python_out=examples/apis/gen             examples/apis/orders.proto
      - name: Start HTTP server
        run: |
          nohup python examples/servers/http_server.py >/tmp/http.log 2>&1 &
          sleep 2
      - name: Start gRPC mock
        run: |
          nohup python examples/servers/grpc_server.py >/tmp/grpc.log 2>&1 &
          sleep 2
      - name: Trace hot path (runtime truth)
        run: |
          u trace module examples/app/hot_path.py run_hot_path -o traces/tour.json
          u lens merge-trace maps/lens.json traces/tour.json -o maps/lens_merged.json
      - name: Generate tour (from merged lens)
        run: |
          u tour maps/lens_merged.json -o tours/PR.md || true
      - name: Run tour (fixture)
        run: |
          set -e
          u tour_run maps/lens_merged.json -f fixtures
